repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: chaos-mesh
  url: https://charts.chaos-mesh.org

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.10.0
  values:
  - controller:
      extraArgs:
        publish-status-address: localhost
      hostPort:
        enabled: true
      publishService:
        enabled: false
      service:
        type: NodePort
        enableHttps: false
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
      watchIngressWithoutClass: true
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/hostname: "sharded-kvs-cluster-control-plane"
      allowSnippetAnnotations: true
- name: chaos-mesh
  namespace: chaos-mesh
  createNamespace: true
  chart: chaos-mesh/chaos-mesh
  version: 2.6.3
  values:
  - dashboard:
      service:
        type: ClusterIP
        clusterIP: None
      securityMode: false
- name: kvs
  namespace: kvs
  createNamespace: true
  chart: ./deploy
  values:
  - shards: 3
    replicas: 3
    shardImage: sharded-kvs-shard
    clusterDomain: localho.st
    chaosMesh:
      enabled: true
