repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: chaos-mesh
  url: https://charts.chaos-mesh.org

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.10.0
  values:
  - controller:
      service:
        enableHttps: false
        nodePorts:
          http: 8080
      allowSnippetAnnotations: true
      extraArgs:
        v: "3"
- name: chaos-mesh
  namespace: chaos-mesh
  createNamespace: true
  chart: chaos-mesh/chaos-mesh
  version: 2.6.3
  values:
  - dashboard:
      service:
        type: ClusterIP
        clusterIP: None
      securityMode: false
- name: kvs
  namespace: kvs
  createNamespace: true
  chart: ./deploy
  values:
  - nodes: 3
    replicas: 4
    nodeImage: sharded-kvs-node
    controllerImage: sharded-kvs-controller
    clusterDomain: localho.st
    chaosMesh:
      enabled: true
