// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.1
// source: protos/fsm.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVFSMLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation int32   `protobuf:"varint,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Key       string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     *string `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *KVFSMLogEntry) Reset() {
	*x = KVFSMLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fsm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVFSMLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVFSMLogEntry) ProtoMessage() {}

func (x *KVFSMLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fsm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVFSMLogEntry.ProtoReflect.Descriptor instead.
func (*KVFSMLogEntry) Descriptor() ([]byte, []int) {
	return file_protos_fsm_proto_rawDescGZIP(), []int{0}
}

func (x *KVFSMLogEntry) GetOperation() int32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *KVFSMLogEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVFSMLogEntry) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type KVFSMSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KvStore map[string]string `protobuf:"bytes,1,rep,name=kv_store,json=kvStore,proto3" json:"kv_store,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *KVFSMSnapshot) Reset() {
	*x = KVFSMSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fsm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVFSMSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVFSMSnapshot) ProtoMessage() {}

func (x *KVFSMSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fsm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVFSMSnapshot.ProtoReflect.Descriptor instead.
func (*KVFSMSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_fsm_proto_rawDescGZIP(), []int{1}
}

func (x *KVFSMSnapshot) GetKvStore() map[string]string {
	if x != nil {
		return x.KvStore
	}
	return nil
}

var File_protos_fsm_proto protoreflect.FileDescriptor

var file_protos_fsm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x64, 0x0a, 0x0d, 0x4b, 0x56,
	0x46, 0x53, 0x4d, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x4b, 0x56, 0x46, 0x53, 0x4d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x6b, 0x76, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4b, 0x56,
	0x46, 0x53, 0x4d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x4b, 0x76, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6b, 0x76, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x4b, 0x76, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x61, 0x70, 0x74,
	0x61, 0x69, 0x6e, 0x49, 0x52, 0x53, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x6b,
	0x76, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_fsm_proto_rawDescOnce sync.Once
	file_protos_fsm_proto_rawDescData = file_protos_fsm_proto_rawDesc
)

func file_protos_fsm_proto_rawDescGZIP() []byte {
	file_protos_fsm_proto_rawDescOnce.Do(func() {
		file_protos_fsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_fsm_proto_rawDescData)
	})
	return file_protos_fsm_proto_rawDescData
}

var file_protos_fsm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_fsm_proto_goTypes = []interface{}{
	(*KVFSMLogEntry)(nil), // 0: protos.KVFSMLogEntry
	(*KVFSMSnapshot)(nil), // 1: protos.KVFSMSnapshot
	nil,                   // 2: protos.KVFSMSnapshot.KvStoreEntry
}
var file_protos_fsm_proto_depIdxs = []int32{
	2, // 0: protos.KVFSMSnapshot.kv_store:type_name -> protos.KVFSMSnapshot.KvStoreEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_fsm_proto_init() }
func file_protos_fsm_proto_init() {
	if File_protos_fsm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_fsm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVFSMLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fsm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVFSMSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_fsm_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_fsm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_fsm_proto_goTypes,
		DependencyIndexes: file_protos_fsm_proto_depIdxs,
		MessageInfos:      file_protos_fsm_proto_msgTypes,
	}.Build()
	File_protos_fsm_proto = out.File
	file_protos_fsm_proto_rawDesc = nil
	file_protos_fsm_proto_goTypes = nil
	file_protos_fsm_proto_depIdxs = nil
}
