// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: protos/shard.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PauseWritesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PauseWritesRequest) Reset() {
	*x = PauseWritesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseWritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseWritesRequest) ProtoMessage() {}

func (x *PauseWritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseWritesRequest.ProtoReflect.Descriptor instead.
func (*PauseWritesRequest) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{0}
}

type PauseWritesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPaused bool `protobuf:"varint,1,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
}

func (x *PauseWritesResponse) Reset() {
	*x = PauseWritesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseWritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseWritesResponse) ProtoMessage() {}

func (x *PauseWritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseWritesResponse.ProtoReflect.Descriptor instead.
func (*PauseWritesResponse) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{1}
}

func (x *PauseWritesResponse) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type RedistributeKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RedistributeKeysRequest) Reset() {
	*x = RedistributeKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedistributeKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedistributeKeysRequest) ProtoMessage() {}

func (x *RedistributeKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedistributeKeysRequest.ProtoReflect.Descriptor instead.
func (*RedistributeKeysRequest) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{2}
}

type RedistributeKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingKeys int32 `protobuf:"varint,1,opt,name=pending_keys,json=pendingKeys,proto3" json:"pending_keys,omitempty"`
}

func (x *RedistributeKeysResponse) Reset() {
	*x = RedistributeKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedistributeKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedistributeKeysResponse) ProtoMessage() {}

func (x *RedistributeKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedistributeKeysResponse.ProtoReflect.Descriptor instead.
func (*RedistributeKeysResponse) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{3}
}

func (x *RedistributeKeysResponse) GetPendingKeys() int32 {
	if x != nil {
		return x.PendingKeys
	}
	return 0
}

type ResumeWritesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeWritesRequest) Reset() {
	*x = ResumeWritesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeWritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeWritesRequest) ProtoMessage() {}

func (x *ResumeWritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeWritesRequest.ProtoReflect.Descriptor instead.
func (*ResumeWritesRequest) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{4}
}

type ResumeWritesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsResumed bool `protobuf:"varint,1,opt,name=is_resumed,json=isResumed,proto3" json:"is_resumed,omitempty"`
}

func (x *ResumeWritesResponse) Reset() {
	*x = ResumeWritesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeWritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeWritesResponse) ProtoMessage() {}

func (x *ResumeWritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeWritesResponse.ProtoReflect.Descriptor instead.
func (*ResumeWritesResponse) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeWritesResponse) GetIsResumed() bool {
	if x != nil {
		return x.IsResumed
	}
	return false
}

type InternalPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key              string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value            string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsRedistribution bool   `protobuf:"varint,3,opt,name=is_redistribution,json=isRedistribution,proto3" json:"is_redistribution,omitempty"`
}

func (x *InternalPutRequest) Reset() {
	*x = InternalPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_shard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalPutRequest) ProtoMessage() {}

func (x *InternalPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_shard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalPutRequest.ProtoReflect.Descriptor instead.
func (*InternalPutRequest) Descriptor() ([]byte, []int) {
	return file_protos_shard_proto_rawDescGZIP(), []int{6}
}

func (x *InternalPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InternalPutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *InternalPutRequest) GetIsRedistribution() bool {
	if x != nil {
		return x.IsRedistribution
	}
	return false
}

var File_protos_shard_proto protoreflect.FileDescriptor

var file_protos_shard_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a,
	0x12, 0x50, 0x61, 0x75, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x13, 0x50, 0x61, 0x75, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3d, 0x0a, 0x18, 0x52, 0x65, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79,
	0x73, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x22,
	0x69, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2b, 0x0a,
	0x11, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x52, 0x65, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xa1, 0x03, 0x0a, 0x08, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x52, 0x50, 0x43, 0x12, 0x30, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x03, 0x50, 0x75, 0x74,
	0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48,
	0x0a, 0x0b, 0x50, 0x61, 0x75, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x52, 0x65, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x61, 0x70,
	0x74, 0x61, 0x69, 0x6e, 0x49, 0x52, 0x53, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d,
	0x6b, 0x76, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_shard_proto_rawDescOnce sync.Once
	file_protos_shard_proto_rawDescData = file_protos_shard_proto_rawDesc
)

func file_protos_shard_proto_rawDescGZIP() []byte {
	file_protos_shard_proto_rawDescOnce.Do(func() {
		file_protos_shard_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_shard_proto_rawDescData)
	})
	return file_protos_shard_proto_rawDescData
}

var file_protos_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_shard_proto_goTypes = []interface{}{
	(*PauseWritesRequest)(nil),       // 0: protos.PauseWritesRequest
	(*PauseWritesResponse)(nil),      // 1: protos.PauseWritesResponse
	(*RedistributeKeysRequest)(nil),  // 2: protos.RedistributeKeysRequest
	(*RedistributeKeysResponse)(nil), // 3: protos.RedistributeKeysResponse
	(*ResumeWritesRequest)(nil),      // 4: protos.ResumeWritesRequest
	(*ResumeWritesResponse)(nil),     // 5: protos.ResumeWritesResponse
	(*InternalPutRequest)(nil),       // 6: protos.InternalPutRequest
	(*GetRequest)(nil),               // 7: protos.GetRequest
	(*DeleteRequest)(nil),            // 8: protos.DeleteRequest
	(*GetResponse)(nil),              // 9: protos.GetResponse
	(*PutResponse)(nil),              // 10: protos.PutResponse
	(*DeleteResponse)(nil),           // 11: protos.DeleteResponse
}
var file_protos_shard_proto_depIdxs = []int32{
	7,  // 0: protos.ShardRPC.Get:input_type -> protos.GetRequest
	6,  // 1: protos.ShardRPC.Put:input_type -> protos.InternalPutRequest
	8,  // 2: protos.ShardRPC.Delete:input_type -> protos.DeleteRequest
	0,  // 3: protos.ShardRPC.PauseWrites:input_type -> protos.PauseWritesRequest
	2,  // 4: protos.ShardRPC.RedistributeKeys:input_type -> protos.RedistributeKeysRequest
	4,  // 5: protos.ShardRPC.ResumeWrites:input_type -> protos.ResumeWritesRequest
	9,  // 6: protos.ShardRPC.Get:output_type -> protos.GetResponse
	10, // 7: protos.ShardRPC.Put:output_type -> protos.PutResponse
	11, // 8: protos.ShardRPC.Delete:output_type -> protos.DeleteResponse
	1,  // 9: protos.ShardRPC.PauseWrites:output_type -> protos.PauseWritesResponse
	3,  // 10: protos.ShardRPC.RedistributeKeys:output_type -> protos.RedistributeKeysResponse
	5,  // 11: protos.ShardRPC.ResumeWrites:output_type -> protos.ResumeWritesResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_protos_shard_proto_init() }
func file_protos_shard_proto_init() {
	if File_protos_shard_proto != nil {
		return
	}
	file_protos_kv_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_shard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseWritesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_shard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseWritesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_shard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedistributeKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_shard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedistributeKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_shard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeWritesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_shard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeWritesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_shard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_shard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_shard_proto_goTypes,
		DependencyIndexes: file_protos_shard_proto_depIdxs,
		MessageInfos:      file_protos_shard_proto_msgTypes,
	}.Build()
	File_protos_shard_proto = out.File
	file_protos_shard_proto_rawDesc = nil
	file_protos_shard_proto_goTypes = nil
	file_protos_shard_proto_depIdxs = nil
}
