// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: protos/sharded_kv.proto

package internal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShardedKVClient is the client API for ShardedKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardedKVClient interface {
	// Get the value for a key
	// As of not, it just returns "Hello, World!"
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type shardedKVClient struct {
	cc grpc.ClientConnInterface
}

func NewShardedKVClient(cc grpc.ClientConnInterface) ShardedKVClient {
	return &shardedKVClient{cc}
}

func (c *shardedKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/protos.ShardedKV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardedKVServer is the server API for ShardedKV service.
// All implementations must embed UnimplementedShardedKVServer
// for forward compatibility
type ShardedKVServer interface {
	// Get the value for a key
	// As of not, it just returns "Hello, World!"
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedShardedKVServer()
}

// UnimplementedShardedKVServer must be embedded to have forward compatible implementations.
type UnimplementedShardedKVServer struct {
}

func (UnimplementedShardedKVServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedShardedKVServer) mustEmbedUnimplementedShardedKVServer() {}

// UnsafeShardedKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardedKVServer will
// result in compilation errors.
type UnsafeShardedKVServer interface {
	mustEmbedUnimplementedShardedKVServer()
}

func RegisterShardedKVServer(s grpc.ServiceRegistrar, srv ShardedKVServer) {
	s.RegisterService(&ShardedKV_ServiceDesc, srv)
}

func _ShardedKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardedKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ShardedKV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardedKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardedKV_ServiceDesc is the grpc.ServiceDesc for ShardedKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardedKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ShardedKV",
	HandlerType: (*ShardedKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ShardedKV_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sharded_kv.proto",
}
