FROM golang:1.22 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y libpcap-dev

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/shard/shard.go cmd/shard/
COPY internal/ internal/

RUN go build -o /app cmd/shard/shard.go


FROM golang:1.22

RUN apt-get update && apt-get install -y dnsutils libpcap-dev libcap2-bin

COPY --from=builder /app/shard /shard

CMD ["/shard", "-port", "8080"]
