FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN echo "#!/bin/sh" > /controller
RUN echo "go run /app/cmd/controller/controller.go -port 8080 \$1 \$2" >> /controller
RUN chmod +x /controller

COPY cmd/controller/controller.go cmd/controller/
COPY internal/ internal/

CMD ["go", "run", "cmd/controller/controller.go", "-port", "8080"]
