FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

# Prevent GLIBC compatibility issues
ENV CGO_ENABLED=0

COPY cmd/controller/controller.go cmd/controller/
COPY internal/ internal/

RUN go build -o /app cmd/controller/controller.go


FROM gcr.io/distroless/base

COPY --from=builder /app/controller /controller

CMD ["/controller", "-port", "8080"]
