{{- range $i, $group := until (int .Values.nodes) }}
apiVersion: v1
kind: Service
metadata:
  name: node-{{ $i }}
  labels:
    app: {{ $.Release.Name }}
    group: node-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $.Release.Name }}
    group: node-{{ $i }}
  clusterIP: None
  ports:
  - name: kv
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: noderpc
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: raft
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: leader
    protocol: TCP
    port: 8083
    targetPort: 8083
---
{{- end }}
{{- range $i, $group := until (int .Values.nodes) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-{{ $i }}-replica
  labels:
    app: {{ $.Release.Name }}
    group: node-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  serviceName: node-{{ $i }}
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      group: node-{{ $i }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        group: node-{{ $i }}
      annotations:
        # Trigger rolling update on sync
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      minReadySeconds: 30
      setHostnameAsFQDN: true
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      containers:
      - name: node
        image: {{ $.Values.nodeImage }}
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
        ports:
        - name: kv
          containerPort: 8080
        - name: noderpc
          containerPort: 8081
        - name: raft
          containerPort: 8082
        env:
        - name: NODE
          value: "{{ $i }}"
        - name: REPLICA
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - sh
        - -c
        - |
          echo "Starting node-$(NODE)-replica-$(REPLICA) with IP $(IP_ADDRESS)"
          for i in $(seq 1 30); do
            echo "Waiting for DNS. Retries: $i"
            nslookup node-$(NODE)-replica-$(REPLICA).node-$(NODE).{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }} >/dev/null && break
            sleep 2
          done
          setcap cap_net_raw,cap_net_admin+eip /node
          /node -node=$(NODE) -replica=$(REPLICA) -nodes={{ $.Values.nodes }} -replicas={{ $.Values.replicas }} -address=$(IP_ADDRESS)
        volumeMounts:
        - name: data-node
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-node
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
---
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-replica
  labels:
    app: {{ $.Release.Name }}
    group: controller
  namespace: {{ $.Release.Namespace }}
spec:
  serviceName: controller
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      group: controller
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        group: controller
      annotations:
        # Trigger rolling update on sync
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      terminationGracePeriodSeconds: 0
      setHostnameAsFQDN: true
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      containers:
      - name: controller
        image: {{ $.Values.controllerImage }}
        imagePullPolicy: Never
        ports:
        - name: kv
          containerPort: 8080
        - name: noderpc
          containerPort: 8081
        - name: raft
          containerPort: 8082
        - name: leader
          containerPort: 8083
        env:
        - name: REPLICA
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        command:
        - /controller
        - -replica=$(REPLICA)
        - -nodes={{ $.Values.nodes }}
        - -replicas={{ $.Values.replicas }}
        volumeMounts:
        - name: data-controller
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-controller
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app: {{ $.Release.Name }}
    group: controller
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $.Release.Name }}
    group: controller
  clusterIP: None
  ports:
  - name: kv
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: noderpc
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: raft
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: leader
    protocol: TCP
    port: 8083
    targetPort: 8083
---
