{{- range $i, $group := until (int .Values.replicaGroups) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: replica-{{ $i }}-node
  labels:
    app: {{ $.Release.Name }}
    group: replica-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  serviceName: replica-{{ $i }}
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      group: replica-{{ $i }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        group: replica-{{ $i }}
    spec:
      terminationGracePeriodSeconds: 0
      setHostnameAsFQDN: true
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      containers:
      - name: node
        image: {{ $.Values.nodeImage }}
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: REPLICA_GROUP
          value: "{{ $i }}"
        - name: REPLICA_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        command:
        - /node
        - --replica-group=$(REPLICA_GROUP)
        - --replica-index=$(REPLICA_INDEX)
---
{{- end }}
{{- range $i, $group := until (int .Values.replicaGroups) }}
apiVersion: v1
kind: Service
metadata:
  name: replica-{{ $i }}
  labels:
    app: {{ $.Release.Name }}
    group: replica-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $.Release.Name }}
    group: replica-{{ $i }}
  clusterIP: None
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
{{- end }}
