{{- range $i, $group := until (int .Values.shards) }}
apiVersion: v1
kind: Service
metadata:
  name: shard-{{ $i }}
  labels:
    app: {{ $.Release.Name }}
    group: shard-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $.Release.Name }}
    group: shard-{{ $i }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: kvrpc
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: shardrpc
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: raftrpc
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: leaderrpc
    protocol: TCP
    port: 8083
    targetPort: 8083
---
{{- end }}
{{- range $i, $group := until (int .Values.shards) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard-{{ $i }}-replica
  labels:
    app: {{ $.Release.Name }}
    group: shard-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  serviceName: shard-{{ $i }}
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      group: shard-{{ $i }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        group: shard-{{ $i }}
      annotations:
        # Trigger rolling update on sync
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      terminationGracePeriodSeconds: 10
      setHostnameAsFQDN: true
      containers:
      - name: shard
        image: {{ $.Values.shardImage }}
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
        ports:
        - name: kvrpc
          containerPort: 8080
        - name: shardrpc
          containerPort: 8081
        - name: raftrpc
          containerPort: 8082
        env:
        - name: SHARD
          value: "{{ $i }}"
        - name: REPLICA
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - bash
        - -c
        - |
          #!/bin/bash
          echo "Starting shard-$(SHARD)-replica-$(REPLICA) with IP $(IP_ADDRESS)"
          for i in $(seq 1 30); do
            echo "Waiting for DNS. Retries: $i"
            nslookup shard-$(SHARD)-replica-$(REPLICA).shard-$(SHARD).{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }} >/dev/null && break
            sleep 2
          done
          setcap cap_net_raw,cap_net_admin+eip /shard

          exec /shard -shard=$(SHARD) -replica=$(REPLICA) -shards={{ $.Values.shards }} -replicas={{ $.Values.replicas }} -address=$(IP_ADDRESS) &
          pid=$!
          echo $pid > /shard.pid
          echo "Shard started as pid $pid"
          trap_sigterm() {
            echo "Received SIGTERM, killing shard-$(SHARD)-replica-$(REPLICA)"
            kill $pid
          }

          trap trap_sigterm SIGTERM

          wait $pid
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "kill -SIGINT $(cat /shard.pid) && sleep 30"]
        volumeMounts:
        - name: data-shard
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-shard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
---
{{- end }}
