FROM golang:1.22 as builder

WORKDIR /app

RUN apt-get update && apt-get install -y libpcap-dev

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/node/node.go cmd/node/
COPY internal/ internal/

RUN go build -o /app cmd/node/node.go


FROM golang:1.22

RUN apt-get update && apt-get install -y dnsutils libpcap-dev libcap2-bin

COPY --from=builder /app/node /node

CMD ["/node", "-port", "8080"]
