---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvctl-captainirs-dev-v1-kvstore
  failurePolicy: Fail
  name: vkvstore-v1.kb.io
  rules:
  - apiGroups:
    - kvctl.captainirs.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kvstores
  sideEffects: None
