# This rule is not used by the project kvctl itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kvctl.captainirs.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kvctl
    app.kubernetes.io/managed-by: kustomize
  name: kvstore-editor-role
rules:
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores/status
  verbs:
  - get
