# This rule is not used by the project kvctl itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kvctl.captainirs.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kvctl
    app.kubernetes.io/managed-by: kustomize
  name: kvstore-viewer-role
rules:
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores/status
  verbs:
  - get
