---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores/finalizers
  verbs:
  - update
- apiGroups:
  - kvctl.captainirs.dev
  resources:
  - kvstores/status
  verbs:
  - get
  - patch
  - update
